### ISSUE TITLE
Can I ask you what kind of tf model did you use?

### ISSUE THREAD

**Issue by pluto2060** [milinddeore/mediapipe-face-detector-cpp#1]
using .tflite file in your repo, it takes almost 50~70ms for inference. I think it would be really helpful if I know the type or structure of the net you used for this project. 
Thanks

**Comment by milinddeore** [comment]
Its a well known BlazeFace model mentioned in this [paper](https://arxiv.org/abs/1907.05047).

**Comment by pluto2060** [comment]
appreciate your comment. Thanks a lot
